# Site settings
name: Statistical Thinking
email: 975909105@qq.com
author: Gu Jia
url: http://yukawax.cn
resume_site: 
github: https://github.com/YukawaX/
baseurl: ""
description: Correlation does not impliy causation.
meta_description: 顾嘉;博客
motto: 
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: YukawaX

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

